// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace testw.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class user : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"user\",\"namespace\":\"testw.avro\",\"fields\":[{\"name\":\"firstn" +
				"ame\",\"type\":\"string\"},{\"name\":\"lastname\",\"type\":\"string\"}]}");
		private string _firstname;
		private string _lastname;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return user._SCHEMA;
			}
		}
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				this._firstname = value;
			}
		}
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				this._lastname = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.firstname;
			case 1: return this.lastname;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.firstname = (System.String)fieldValue; break;
			case 1: this.lastname = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
